### ISSUE TITLE
Typing "2 characters query" results in error

### ISSUE THREAD

**Issue by LampPrinter** [isometry/alfred-pipe#4]
The images will explain the issue better.

![CleanShot -  (Finder) - 28 April 2023 at 12 55 29](https://user-images.githubusercontent.com/7559328/235082589-40deff6b-082a-4731-a1f7-aa7e9680baa7.png)

![CleanShot -  (Finder) - 28 April 2023 at 12 55 40](https://user-images.githubusercontent.com/7559328/235082614-d59c32b4-489c-4989-944f-fcaca28bb3c5.png)

![CleanShot -  (Finder) - 28 April 2023 at 12 55 50](https://user-images.githubusercontent.com/7559328/235082631-dcf1caf8-93b6-4c46-8b8c-ab205250182d.png)

```
Pipe[Script Filter] Queuing argument 'ba'
[12:50:03.302] Pipe[Script Filter] Script with argv 'ba' finished
[12:50:03.307] ERROR: Pipe[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/XYZ/Alfred.alfredpreferences/workflows/user.workflow.FBDAEC5D-F9C3-4F35-826F-D389441A644A/pipe.py", line 150, in <module>
    print(complete())
          ^^^^^^^^^^
  File "/Users/XYZ/Alfred.alfredpreferences/workflows/user.workflow.FBDAEC5D-F9C3-4F35-826F-D389441A644A/pipe.py", line 146, in complete
    return alfred.xml(results, maxresults=max_results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XYZ/Alfred.alfredpreferences/workflows/user.workflow.FBDAEC5D-F9C3-4F35-826F-D389441A644A/alfred.py", line 65, in xml
    root.append(item.xml())
                ^^^^^^^^^^
  File "/Users/XYZ/Alfred.alfredpreferences/workflows/user.workflow.FBDAEC5D-F9C3-4F35-826F-D389441A644A/alfred.py", line 32, in xml
    SubElement(item, attribute, attributes).text = value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SubElement() argument 3 must be dict, not str
```

**Comment by isometry** [comment]
Thanks for the report. I'll try to get to the bottom of this…

**Comment by isometry** [comment]
@LampPrinter : https://github.com/isometry/alfred-pipe/releases/tag/v2.1 should fix the issue.
